<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DiscordRPCBridge_Wine</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Title>Discord RPC Bridge for Wine</Title>
    <Version>0.0.1</Version>
    <Authors>Bronya Rand</Authors>
    <Company>Bronya Rand</Company>
    <Description>A Discord Rich Presence relay bridge for Wine/CrossOver builds that don't suppor AF_UNIX.</Description>
    <Copyright>Copyright 2026 Bronya Rand</Copyright>
    <PackageProjectUrl>https://github.com/Bronya-Rand/DiscordRPCBridge-Wine</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/Bronya-Rand/DiscordRPCBridge-Wine</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>discord,rpc,wine,proton,ipc,crossover,linux,mac,ffxiv,xiv</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>False</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>False</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\icon.png" Pack="true" PackagePath="\" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
